version: '3.6'
services:
  cow:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/maciejbekascowsay:latest
    container_name: "cow"
    ports:
    - 2137:8080
    networks:
     - mynet
  nginx:
    build: .
#    image: nginx:1.23.1
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot:/etc/letsencrypt/:rw
#     - ./app/conf/nginx.conf:/etc/nginx/nginx.conf
#     - ./app/maven-data/webapp:/usr/share/nginx/html
#     - ./app/src/main/resources/static/index.html:/usr/share/nginx/html/index.html
    networks:
     - mynet
    depends_on:
     - cow
networks:
  mynet:
    name: mynet
volumes:
  certbot:
    name: certbot